#!/usr/bin/env python
# -*- encoding: utf8 -*-

print("Question: What goes clip?\nAnswer: A one legged horse.")
print("Here is a speech mark: \" and here is a slash: \\")
print('I say "High", you say "Low". You say "Why?" and I say "I don\'t know". Oh no.')
print('동균이는 "바보"다.')
print("동균이는 \"바보\"다.")

print(20//8)
print(20%3)
print(20-6-2)
print("111을 4로 나누면?", 111/4)
print("11을 4로 나누면?", 11/4)

lines=0
while lines < 50:
    print("나는 수업 시간에 프러그래밍을 하지 않겠습니다.")
    lines=lines+1

print("나는 수업 시간에 프로그래밍을 하지 않겠습니다.\n"*50)

number=1
while number < 101:
    print(number)
    number=number+1



number=2
while number<21:
    print(number)
    number=number+1

number=1
while number<11:
    print(number*2)
    number=number+1

number=1
while number<11:
    print(number,"x 5 =",number*5)
    number=number+1


number=1
while number < 101:
    print(number)
    number = number+1

number=1
while number <= 100:
    print(number)
    number = number+1

number=1
while 101>number:
    print(number)
    number = number+1


